# Generated by Django 4.2.16 on 2024-09-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employe", "0027_contrat_nature_revenu_contrat_type_personnel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FichePoste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("competences_requises", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PlanRecrutement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poste", models.CharField(max_length=100)),
                ("date_prevue", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ReferentielCompetences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competence", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("niveau", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Talent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competences_cles",
                    models.TextField(default="compétences non définis"),
                ),
                ("realisations", models.TextField(default="réalisations non définis")),
                (
                    "potentiel",
                    models.CharField(
                        choices=[
                            ("Faible", "Faible"),
                            ("Moyen", "Moyen"),
                            ("Élevé", "Élevé"),
                            ("Exceptionnel", "Exceptionnel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("objectifs", models.TextField(default="Objectifs non définis")),
                (
                    "plan_developpement",
                    models.TextField(default="plan de developpement non définis"),
                ),
                ("date_evaluation", models.DateField()),
                (
                    "employe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuiviCarriere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_embauche", models.DateField()),
                ("poste_actuel", models.CharField(max_length=100)),
                ("historique_postes", models.TextField()),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PointagePresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure_arrivee", models.TimeField()),
                ("heure_depart", models.TimeField()),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_evaluation", models.DateField()),
                (
                    "objectifs_atteints",
                    models.TextField(default="Objectifs non définis"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Insuffisant"),
                            (2, "À améliorer"),
                            (3, "Satisfaisant"),
                            (4, "Très bon"),
                            (5, "Exceptionnel"),
                        ]
                    ),
                ),
                ("commentaires", models.TextField(default="commentaires non définis")),
                (
                    "talent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="gpec.talent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_evaluation", models.DateField()),
                (
                    "performance_poste",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "qualites_relationnelles",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "engagement_motivation",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "autonomie",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "conformite_organisationnelle",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("commentaires_collaborateur", models.TextField(blank=True)),
                ("commentaires_superieur", models.TextField(blank=True)),
                ("formations_suivies", models.TextField(blank=True)),
                ("besoins_formation", models.TextField(blank=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
                (
                    "evaluateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations_effectuees",
                        to="employe.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DossierPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cv", models.FileField(upload_to="cv/")),
                ("diplomes", models.FileField(upload_to="diplomes/")),
                ("certificats", models.FileField(upload_to="certificats/")),
                (
                    "employe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
            ],
        ),
    ]
