# Generated by Django 4.2.16 on 2024-09-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0027_contrat_nature_revenu_contrat_type_personnel_and_more"),
        ("gpec", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("CV", "Curriculum Vitae"),
                            ("DIPLOME", "Diplôme"),
                            ("CERTIFICAT", "Certificat de travail"),
                            ("FORMATION", "Attestation de formation"),
                            ("AUTRE", "Autre document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("fichier", models.FileField(upload_to="documents_personnels/")),
                ("date_ajout", models.DateField(auto_now_add=True)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="employe.employe",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DossierPersonnel",
        ),
    ]
