# Generated by Django 4.2.16 on 2024-09-20 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0028_secteuractivite_employe_secteur_activite"),
        ("gpec", "0002_documentpersonnel_delete_dossierpersonnel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MouvementPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_mouvement", models.DateField()),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("DEPART_RETRAITE", "Départ en retraite"),
                            ("LICENCIEMENT", "Licenciement"),
                            ("DEMISSION", "Démission"),
                            ("DECES", "Décès"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raison", models.TextField()),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="employe.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvolutionCarriere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_changement", models.DateField()),
                (
                    "type_evolution",
                    models.CharField(
                        choices=[
                            ("PROMOTION", "Promotion"),
                            ("MUTATION", "Mutation"),
                            ("RECLASSEMENT", "Reclassement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "ancien_poste",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anciens_postes",
                        to="gpec.poste",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evolutions_carriere",
                        to="employe.employe",
                    ),
                ),
                (
                    "nouveau_poste",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nouveaux_postes",
                        to="gpec.poste",
                    ),
                ),
            ],
        ),
    ]
