# Generated by Django 4.2.16 on 2024-09-21 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("gpec", "0003_poste_mouvementpersonnel_evolutioncarriere"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planrecrutement",
            name="date_prevue",
        ),
        migrations.RemoveField(
            model_name="planrecrutement",
            name="poste",
        ),
        migrations.AddField(
            model_name="planrecrutement",
            name="competences_requises",
            field=models.TextField(default="compétences requises non définis"),
        ),
        migrations.AddField(
            model_name="planrecrutement",
            name="date_debut",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="planrecrutement",
            name="date_fin",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="planrecrutement",
            name="departement",
            field=models.CharField(default="management", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planrecrutement",
            name="nombre_postes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="planrecrutement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_COURS", "En cours"),
                    ("TERMINE", "Terminé"),
                    ("ANNULE", "Annulé"),
                ],
                default="EN_COURS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="planrecrutement",
            name="titre",
            field=models.CharField(default="2020", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="planrecrutement",
            name="description",
            field=models.TextField(default="descriptions non définis"),
        ),
        migrations.AlterField(
            model_name="pointagepresence",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="CandidatPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=20)),
                ("cv", models.FileField(upload_to="cvs/")),
                (
                    "date_candidature",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("RECU", "Reçu"),
                            ("EN_COURS", "En cours"),
                            ("ACCEPTE", "Accepté"),
                            ("REFUSE", "Refusé"),
                        ],
                        default="RECU",
                        max_length=20,
                    ),
                ),
                ("commentaires", models.TextField(blank=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidats",
                        to="gpec.planrecrutement",
                    ),
                ),
            ],
        ),
    ]
