# Generated by Django 4.2.16 on 2024-09-21 06:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0028_secteuractivite_employe_secteur_activite"),
        ("gpec", "0004_remove_planrecrutement_date_prevue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField(blank=True, null=True)),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "type_absence",
                    models.CharField(
                        choices=[
                            ("CONGE", "Congé"),
                            ("MALADIE", "Maladie"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, default="Justification non notifié"),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="employe.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("heure_arrivee", models.TimeField(blank=True, null=True)),
                ("heure_depart", models.TimeField(blank=True, null=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="employe.employe",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PointagePresence",
        ),
    ]
