# Generated by Django 4.2.16 on 2024-09-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0028_secteuractivite_employe_secteur_activite"),
        ("gpec", "0005_absence_pointage_delete_pointagepresence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ficheposte",
            name="description",
        ),
        migrations.AddField(
            model_name="ficheposte",
            name="activites_principales",
            field=models.TextField(default="Activités principales non spécifié"),
        ),
        migrations.AddField(
            model_name="ficheposte",
            name="date_creation",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="ficheposte",
            name="date_mise_a_jour",
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="ficheposte",
            name="departement",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ficheposte",
            name="experience_requise",
            field=models.TextField(default="Pas d'expérience reqise"),
        ),
        migrations.AddField(
            model_name="ficheposte",
            name="formation_requise",
            field=models.TextField(default="Formation non spécifié"),
        ),
        migrations.AddField(
            model_name="ficheposte",
            name="missions_principales",
            field=models.TextField(default="Mission non spécifié"),
        ),
        migrations.AddField(
            model_name="ficheposte",
            name="superieur_hierarchique",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="ficheposte",
            name="competences_requises",
            field=models.TextField(default="compétences requises non spécifié"),
        ),
        migrations.AlterField(
            model_name="ficheposte",
            name="titre",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="EmployePoste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_attribution", models.DateField(auto_now_add=True, null=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
                (
                    "fiche_poste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gpec.ficheposte",
                    ),
                ),
            ],
        ),
    ]
