# Generated by Django 4.2.16 on 2024-09-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0028_secteuractivite_employe_secteur_activite"),
        ("gpec", "0006_remove_ficheposte_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(default="Pas de compétence d'abord")),
                ("categorie", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NiveauCompetence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niveau",
                    models.IntegerField(
                        choices=[
                            (1, "Débutant"),
                            (2, "Intermédiaire"),
                            (3, "Avancé"),
                            (4, "Expert"),
                        ]
                    ),
                ),
                ("date_evaluation", models.DateField(auto_now=True, null=True)),
                (
                    "competence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gpec.competence",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
            ],
            options={
                "unique_together": {("competence", "employe")},
            },
        ),
        migrations.DeleteModel(
            name="ReferentielCompetences",
        ),
    ]
