# Generated by Django 4.2.16 on 2024-10-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpec", "0007_competence_niveaucompetence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="justification",
            field=models.TextField(blank=True, default="Notifiez une justification"),
        ),
        migrations.AlterField(
            model_name="competence",
            name="description",
            field=models.TextField(default="Décrire vos compétences"),
        ),
        migrations.AlterField(
            model_name="ficheposte",
            name="activites_principales",
            field=models.TextField(default="Spécifiez l'activitée principale"),
        ),
        migrations.AlterField(
            model_name="ficheposte",
            name="competences_requises",
            field=models.TextField(default="Spécifiez des compétences requises"),
        ),
        migrations.AlterField(
            model_name="ficheposte",
            name="experience_requise",
            field=models.TextField(default="Spécifiez vos expériences"),
        ),
        migrations.AlterField(
            model_name="ficheposte",
            name="formation_requise",
            field=models.TextField(default="Spécifiez des formations"),
        ),
        migrations.AlterField(
            model_name="ficheposte",
            name="missions_principales",
            field=models.TextField(default="spécifiiez une mission"),
        ),
        migrations.AlterField(
            model_name="performance",
            name="commentaires",
            field=models.TextField(default="Ajoutez des commentaires"),
        ),
        migrations.AlterField(
            model_name="performance",
            name="objectifs_atteints",
            field=models.TextField(default="Ajoutez des objectifs"),
        ),
        migrations.AlterField(
            model_name="planrecrutement",
            name="competences_requises",
            field=models.TextField(default="Ajoutez des compétences requises"),
        ),
        migrations.AlterField(
            model_name="talent",
            name="competences_cles",
            field=models.TextField(default="Ajoutez des compétences"),
        ),
        migrations.AlterField(
            model_name="talent",
            name="objectifs",
            field=models.TextField(default="Ajoutez des objectifs"),
        ),
        migrations.AlterField(
            model_name="talent",
            name="plan_developpement",
            field=models.TextField(default="Ajoutez un plan de developpement"),
        ),
        migrations.AlterField(
            model_name="talent",
            name="realisations",
            field=models.TextField(default="Ajoutez des réalisations"),
        ),
    ]
