# Generated by Django 4.2.7 on 2023-12-30 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[("T", "Technicien"), ("I", "Ingénieur")],
                        max_length=1,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diplome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diplome",
                    models.CharField(
                        choices=[
                            ("CEP", "Certificat d'Edude Primaire"),
                            ("BEPC", "Brevet d'Etude du Premier Cycle"),
                            ("CQP", "Certificat de Qualification professionnelle"),
                            ("BEB", "Brevet d'Etude Professionnelle"),
                            ("CAP", "Certificat d'Aptitude Professionnelle"),
                            ("BAC", "Baccalauriat"),
                            ("LIC", "Licence"),
                            ("MAS", "Master"),
                            ("DOC", "Doctorat"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SituationMatrimoniale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situation_matrimoniale",
                    models.CharField(
                        choices=[
                            ("M", "Marié"),
                            ("C", "Célibataire"),
                            ("V", "Veuve"),
                            ("VE", "Veuf"),
                            ("D", "Divorcé"),
                        ],
                        max_length=2,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specialite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        choices=[
                            ("Math", "Mathématique"),
                            ("C", "Chimie"),
                            ("D", "Droit"),
                            ("RH", "Resource Humaine"),
                            ("GC", "Gestion Commerciale"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denomination", models.CharField(max_length=255)),
                ("description_structure", models.TextField()),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("adresse", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TypeContrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("CDD", "Contrat à Durée Déterminé"),
                            ("CDI", "Contrat à Durée Indéterminé"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenoms", models.CharField(max_length=255)),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(max_length=255)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=10
                    ),
                ),
                ("nombre_enfant", models.IntegerField()),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("adresse", models.TextField()),
                ("cv", models.FileField(blank=True, null=True, upload_to="cvs/")),
                (
                    "lettre_motivation",
                    models.FileField(
                        blank=True, null=True, upload_to="lettres_motivation/"
                    ),
                ),
                (
                    "diplome",
                    models.FileField(blank=True, null=True, upload_to="diplomes/"),
                ),
                ("numero_cnss", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "numero_matricule",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.categorie",
                    ),
                ),
                (
                    "dernier_diplome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.diplome",
                    ),
                ),
                (
                    "situation_matrimoniale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.situationmatrimoniale",
                    ),
                ),
                (
                    "specialite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.specialite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_poste", models.TextField()),
                ("description_profil", models.TextField()),
                ("lieu_affectation", models.CharField(max_length=255)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "diplome_requis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.diplome",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.employe",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.structure",
                    ),
                ),
                (
                    "type_contrat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employe.typecontrat",
                    ),
                ),
            ],
        ),
    ]
