# Generated by Django 4.2.7 on 2024-01-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrat",
            name="employe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.employe",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="adresse",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="structure",
            name="adresse",
            field=models.CharField(max_length=255),
        ),
    ]
