# Generated by Django 4.2.7 on 2024-01-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0002_alter_contrat_employe_alter_employe_adresse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="categorie",
            field=models.CharField(
                choices=[("Technicien", "Technicien"), ("Ingénieur", "Ingénieur")],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="situationmatrimoniale",
            name="situation_matrimoniale",
            field=models.CharField(
                choices=[
                    ("Marié", "Marié"),
                    ("Célibataire", "Célibataire"),
                    ("Veuve", "Veuve"),
                    ("Veuf", "Veuf"),
                    ("Divorcé", "Divorcé"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="specialite",
            name="specialite",
            field=models.CharField(
                choices=[
                    ("Mathématique", "Mathématique"),
                    ("Chimie", "Chimie"),
                    ("Droit", "Droit"),
                    ("Resource Humaine", "Resource Humaine"),
                    ("Gestion Commerciale", "Gestion Commerciale"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
