# Generated by Django 5.0.3 on 2024-09-07 17:58

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0026_pointage_nb_jour_travail_normal"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="nature_revenu",
            field=models.CharField(
                choices=[("S", "Salaire"), ("R", "Rappel"), ("A", "Autres")],
                default="S",
                max_length=1,
                verbose_name="Nature du revenu",
            ),
        ),
        migrations.AddField(
            model_name="contrat",
            name="type_personnel",
            field=models.CharField(
                choices=[
                    ("PER", "Permanent"),
                    ("JOU", "Journalier"),
                    ("STA", "Stagiaire"),
                ],
                default="PER",
                max_length=3,
                verbose_name="Type de personnel",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="description_poste",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="description_profil",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="diplome_requis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.diplome",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="employe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.employe",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.structure",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="type_contrat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.typecontrat",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.categorie",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="dernier_diplome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.diplome",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="lieu_naissance",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="nom_mere",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="nom_pere",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="option",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="personne_prevenir",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="profession",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="situation_matrimoniale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.situationmatrimoniale",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="sous_couvert",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="specialite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employe.specialite",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="telephone_prevenir",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
