# Generated by Django 4.2.16 on 2024-10-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0028_secteuractivite_employe_secteur_activite"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="duree",
            field=models.IntegerField(
                blank=True, help_text="Durée en mois pour CDD", null=True
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="date_debut",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
    ]
