# Generated by Django 4.2.16 on 2024-10-07 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0029_contrat_duree_alter_contrat_date_debut_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contrat",
            name="duree",
        ),
    ]
