# Generated by Django 4.2.16 on 2024-10-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0030_remove_contrat_duree"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="age_legal_retraite",
            field=models.IntegerField(default=62),
        ),
        migrations.AddField(
            model_name="contrat",
            name="date_retraite_prevue",
            field=models.DateField(blank=True, null=True),
        ),
    ]
